spring:
  application:
    name: AskifyAPP
  data:
    mongodb:
      host: localhost
      port: 27017
      database: askify_db
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: view-count-consumer
  elasticsearch:
    uris: http://localhost:9200

